pipeline {
    agent {
        docker {
            image 'node:16-alpine'
            label 'any'
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}

